# Generated by Django 2.2.12 on 2021-06-09 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_firstname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_lastname',
            new_name='lastname',
        ),
    ]
