# Generated by Django 2.2.12 on 2021-06-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_auto_20210609_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='updated_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
